### ISSUE TITLE
Support for select elements?

### ISSUE THREAD

**Issue by nickw** [djhi/meteor-autoform-materialize#1]
It looks like you have to add a `browser-default` class to normal `<select>` elements to get them to show up in Materialize. Otherwise Materialize is using a fake select / dropdown UI by default.

Have you tested your package with `<select>` elements yet?

**Comment by djhi** [comment]
Select are working fine in my apps but I still have to work on some others
(checkboxes and radio will be published tomorrow)

I like the dropdown select but I'll see if I can support both modes

**Comment by djhi** [comment]
You can add the class `browser-default` by yourself and it still works smoothly.

```
{{> afFieldInput
    name="fieldname" 
    class="browser-default" }}
```
