### ISSUE TITLE
"select-multiple" fields support?

### ISSUE THREAD

**Issue by laurentpayot** [djhi/meteor-autoform-materialize#10]
Hi,I love this project but is the support of "select-multiple" type of fields planned anytime soon? ( "select-multiple" works like a mere "select" for now)

**Comment by djhi** [comment]
Ask the guys at materialize ^^ Their dropdown does not support multiple
select, so you have to enable browser-default as specified in their doc.
Haven't tested it though. Let me know how it goes. If it does work, I'll
remove the warning and the materialize select initialization from it

Le lun. 30 mars 2015 à 16:49, Laurent Payot notifications@github.com a
écrit :

**Comment by laurentpayot** [comment]
I use quickForm so I tested it by editing generated html in Firefox. I added the "multiple" attribute and the "browser-default" class to the select tag. It worked: you can select multiple options and once the form is submitted the multiple options are saved. But of course the "browser-default field" is kind of ugly and the multiple selected options are not displayed at the top...
