### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by cunneen** [djhi/meteor-autoform-materialize#100]
Is this project still alive? 

[https://github.com/djhi/meteor-autoform-materialize/graphs/commit-activity]()

**Comment by djhi** [comment]
Hey, I don't do much meteor these days and when I do I use React. I won't spent time on this repository but I would happily transfer it to anyone willing to work on it. Interested ?

**Comment by cunneen** [comment]
Thanks for clarifying. I don't have a lot of time to manage the project, but I do find it very useful.
