### ISSUE TITLE
materialize icons don't work

### ISSUE THREAD

**Issue by cunneen** [djhi/meteor-autoform-materialize#101]
Materialize has changed the way icons are specified in html, to be compatible with Google's material icons.

So references to e.g. 

`<i class="mdi-content-add"></i>`

Need to be changed to:

`<i class="material-icons">add</i>`

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize). Thanks @mozfet
