### ISSUE TITLE
add data-required on afFormGroup div

### ISSUE THREAD

**Issue by diegonc** [djhi/meteor-autoform-materialize#103]
Back in version 5.0.0[1] autoform added a `data-required` attribute to the afFromGroup container div which allows to add a required marker to labels through CSS.

Can this be implemented here? The current state makes it difficult to add such marker to select fields.

[1] https://github.com/aldeed/meteor-autoform/commit/0ea0fb24ccdc40dbd8da16f2b696d2b5bafc803b

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize). Thanks @mozfet
