### ISSUE TITLE
Multiple date picking ?

### ISSUE THREAD

**Issue by TheYojimbo** [djhi/meteor-autoform-materialize#104]
Hello,

First, thank you very much for this great work.

So I've been browsing the web for most of the afternoon searching for something that fit my needs, and I've been unsuccessful so far. I'd like the possibility to select multiple dates on a calendar, and I was wondering if it could be possible with your package.

I've tried with a node package, but couldn't make it work on my project, and aldeed bootstrap-datepicker does support the feature, but materialize and bootstrap dont mix well.

Please tell me I missed something ! I really need to have this feature on my project.

Thanks in advance for your time,

Yojimbo.

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize). Thanks @mozfet
