### ISSUE TITLE
pickadate is not a function Error

### ISSUE THREAD

**Issue by Chey47** [djhi/meteor-autoform-materialize#107]
Hey , Great package but i have a little problem with it.

Anytime i pick a date i get this : pickadate is not a function Error , Espacialy when it tries to call the Close function which leaves the datepicker always open :(

Error on this line : `return $(this).pickadate('picker').close();  ` 

Can you please help ?

**Comment by ziaulrehman40** [comment]
@Chey47 Any solution?

**Comment by Chey47** [comment]
Hey , yeah for the "pickadate is not a function Error" , it was because i was including manually another Jquery script which screwed up everything. Using meteor's jquery fixed that.

for the "datepicker always open" problem i added this line in my client lib directory (First folder to be loaded in client  : 

```
$.extend($.fn.pickadate.defaults, {
        onClose: function() {
           $(document.activeElement).blur();
        }
});
 
```

Hope this helped you.

**Comment by ziaulrehman40** [comment]
Well, thanks for the update. But i don't know how would i figure out which script is messing things up. i  of js being used in my project. So, i think i should look for another library maybe :/
[A similar issue being discussed here.](https://github.com/janmarek/WebLoader/issues/119#issuecomment-276631965)

**Comment by djhi** [comment]
I no longer use Meteor and won't be updating this project anymore. If anyone is interested in taking care of it, I'll gladly transfer ownership.

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize). Thanks @mozfet
