### ISSUE TITLE
Could upgrade to last of AutoForm?

### ISSUE THREAD

**Issue by thearabbit** [djhi/meteor-autoform-materialize#108]
Could upgrade to last of AutoForm?

**Comment by jfhenon** [comment]
Is this package maintained?

**Comment by djhi** [comment]
I no longer use Meteor and won't be updating this project anymore. If anyone is interested in taking care of it, I'll gladly transfer ownership.

**Comment by thearabbit** [comment]
Wow `I no longer use Meteor`.
what the new for you?

**Comment by djhi** [comment]
First, as most apps, my apps don't need real time client updates.

I use koa on serverside with a postgresql database and apollo. 
I use react/redux/apollo on client.

**Comment by thearabbit** [comment]
Thanks for your sharing.

**Comment by djhi** [comment]
No problem. Interested in taking over this project ?

**Comment by mozfet** [comment]
This package will be maintained by me going forward. I will be using it in a commercial product, so I expect to have it it tip-top shape within a few weeks.

**Comment by mozfet** [comment]
PS: I have started using this repo with (and have not foud any major issues... yet):
METEOR@1.4.2.3
aldeed:autoform@5.1.2
aldeed:collection2-core@2.0.0
aldeed:simple-schema@1.3.3
aldeed:template-extension@4.0.0
materialize:materialize@0.98.0
mdg:validated-method@1.1.0
