### ISSUE TITLE
weird behavior with select

### ISSUE THREAD

**Issue by yanndebelgique** [djhi/meteor-autoform-materialize#11]
Hi,

I have an issue with select-dropdown. It doesn't show at all where it's supposed to be :-(

Here is a picture

![screenshot 2015-04-04 21 26 21](https://cloud.githubusercontent.com/assets/2687189/6994238/9f76cf56-db11-11e4-9256-6d78cd6f96fa.png)

code :

```
{{> quickForm schema=this.schema id=this.name type="method" omitFields="question" meteormethod="questions/answer"}}
```

Btw Don't know what is going on and if I want to inspect the dropdown I can't because it disappears on me when I click so I cant use element inspector.

**Comment by djhi** [comment]
How do you include materialize files ?

**Comment by yanndebelgique** [comment]
with the materialize:materialize package

**Comment by djhi** [comment]
Never seen this prb before. Can you make a repository with a reproduction
of this prb ?

**Comment by yanndebelgique** [comment]
sorry sorry sorry. It was my css that was the pb... Thanks for this very cool package you saved me ALOT of time!!!

**Comment by djhi** [comment]
I'm glad you got it working. Please tell me if you see anything that can be
improved.

**Comment by yanndebelgique** [comment]
Ok will do
