### ISSUE TITLE
Add input ID to label focus works fine

### ISSUE THREAD

**Issue by jadsonlourenco** [djhi/meteor-autoform-materialize#12]
When click on a **label** it should focus on the corresponding input, but only using the `name` attribute in this field focus effect does not work because it needs the **ID** attribute.
So, the label has the attr **for**, but the input need the **id**.

I know that we can add it manually, but this theme auto generate the _label_ attr **for** with the input name from schema, that is unique like the **id attr** need be. 
I hope you understand my vision. Any way thank you so much for this package and good work.

**Comment by djhi** [comment]
It's done already. Have you found a label without id ?

**Comment by jadsonlourenco** [comment]
No, I get the input without **ID**:

```
{{> afQuickField name="email"}}

// return
<div class="input-field">    
    <input type="text" name="email" required>     
    <label for="email">Your E-mail</label>    
</div>
```

The input don't has an ID, you see different?

**Comment by djhi** [comment]
I'll check that asap

**Comment by djhi** [comment]
Are you using the last autoform too ?

On the [playground](https://github.com/djhi/meteor-autoform-materialize-playground) which is running [here](http://autoform-materialize-playground.meteor.com/), you can see that ids are generated correctly.

**Comment by jadsonlourenco** [comment]
Yes man, the all problem is that, autoform not update of 4.2 to 5.0 version, I need add one flag on meteor cmd to do that. So problem solved! Thank you so much!

**Comment by djhi** [comment]
in your `.meteor/packages` file, add autoform like this:

```
aldeed:autoform@5.1.2
```
