### ISSUE TITLE
Add Class Invalid

### ISSUE THREAD

**Issue by jadsonlourenco** [djhi/meteor-autoform-materialize#13]
On Materialize to make the input with **red underline** after validation fail need add this class **invalid** to input.

**Comment by djhi** [comment]
Thx for reporting this. I'll add it asap

**Comment by djhi** [comment]
I haven't been able to make it work with pickadate and dropdowns but it should now work for all other inputs. You may have to implement it yourself for custom inputs

**Comment by jadsonlourenco** [comment]
Oh man thank you! 
I need learn a bit about the helpers of autoform and then I can help with it because is important to have to all inputs, but for now I will show a "toast" message for this inputs that don't have autovalidation.

**Comment by djhi** [comment]
They have validation as you can see on the playground but I haven't find a
way to add the `invalid` class without causing problems.

**Comment by djhi** [comment]
In case you don't know, a playground is available here:
https://github.com/djhi/meteor-autoform-materialize-playground/tree/master

Le mer. 8 avr. 2015 à 15:07, Gildas Garcia gildas.garcia@gmail.com a
écrit :

> They have validation as you can see on the playground but I haven't find a
> way to add the `invalid` class without causing problems.
>

**Comment by jadsonlourenco** [comment]
Yes I saw, I will see it soon, maybe use other class name, and add custom styles, but need see on Materialize repo about that.

**Comment by djhi** [comment]
If anyone ask, I can also add the `valid` class

**Comment by boustanihani** [comment]
I just posted a question about this: https://github.com/Dogfalo/materialize/issues/1454

**Comment by boustanihani** [comment]
Have you tried using the **"Custom Error Messages"** (`data-error`) for dropdowns ?? This has been introduced in v0.97

Check: http://materializecss.com/forms.html
