### ISSUE TITLE
Switch labels

### ISSUE THREAD

**Issue by coniel** [djhi/meteor-autoform-materialize#15]
When switches are in the false position the label drops down covering them: 
![screen shot 2015-04-16 at 11 47 56](https://cloud.githubusercontent.com/assets/1728027/7177489/c4abb094-e42f-11e4-8ffe-3b1871a9c19b.png)

Also, is there a way to not display the true and false labels?

**Comment by djhi** [comment]
That's strange, i have some very long titles and i don't have this prb.

Have you tried  to pass empty strings ?

Le jeu. 16 avr. 2015 10:59, Oscar Coniel notifications@github.com a
écrit :

**Comment by coniel** [comment]
The thing covering it is the input label (not the true/false labels). This is what it's like when enabled:
![screen shot 2015-04-16 at 11 48 01](https://cloud.githubusercontent.com/assets/1728027/7177763/e92f2aca-e431-11e4-8550-dca7ccc31f6c.png)

I did try and pass empty string (as well as false and null) to disable to true/false labels, but it reverts to the default "Off/On" labels.

**Comment by djhi** [comment]
Oh right, can you try to pass `label-class="active"` on your quickfield ?

Le jeu. 16 avr. 2015 à 11:15, Oscar Coniel notifications@github.com a
écrit :

**Comment by coniel** [comment]
Doesn't make a difference.

**Comment by coniel** [comment]
The active class gets removed when the form is generated. The label is only in that position when the form is generated with the value set to false. When it starts off as true, the label is in the correct place. Also, when you go from false to true the label goes up, and when you go back again the label stays in the right place.

**Comment by coniel** [comment]
Actually (sorry for spamming), when the form starts off as true, the label is in the correct position, but when you switch to false it goes down and then doesn't go back up when switching to true.

So basically:
- when the original value is true, label start in the right place but falls down when switching to false (and stays up when switching back and forth again)
- when the original value is false, label starts in wrong position but goes up when switching to true (and stays up when switching back and forth again)
- adding `label-class="active"` has no effect

**Comment by djhi** [comment]
Ok, thx for this report. I'll take a look asap.

Le jeu. 16 avr. 2015 11:45, Oscar Coniel notifications@github.com a
écrit :

**Comment by djhi** [comment]
Ok, here's what will do the next patch to match materialize usage of switch ([doc](http://materializecss.com/forms.html#switches)):
- Don't apply the `input-field` CSS class to the form-group containing the switch
- Don't add label for switches

> Also, is there a way to not display the true and false labels?

No, as you can see in the materialize doc, you must have both labels. You can however pass empty strings if you like. Check this package README
