### ISSUE TITLE
Datepicker in modal is cut off

### ISSUE THREAD

**Issue by benan789** [djhi/meteor-autoform-materialize#20]
I've tried setting datepicker container with this on render but does not work.

$('.datepicker').pickadate({
    container: 'body'
});

**Comment by djhi** [comment]
I think this is a materialize prb, not a meteor-autoform-materialize one.

**Comment by jadsonlourenco** [comment]
For me this works:

```
autoform: {
  type: 'pickadate',
    pickadateOptions: {
      container: 'body'
    }
 }
```

Define options on schema, not in jQuery format.

**Comment by djhi** [comment]
Thanks Jadson, I should have noticed

**Comment by benan789** [comment]
Thanks Jadson! Worked perfectly!
