### ISSUE TITLE
Select not working in the 0.0.18

### ISSUE THREAD

**Issue by charandas** [djhi/meteor-autoform-materialize#27]
As mentioned [here](https://github.com/orionjs/orion/issues/175)

The call to `material_select` never happens. Thoughts?

**Comment by charandas** [comment]
I breakpoint in [L188](https://github.com/djhi/meteor-autoform-materialize/blob/master/materialize.coffee#L188) but it never seems to occur.

**Comment by charandas** [comment]
Ping - anyone?

**Comment by djhi** [comment]
Sorry, I'm currently very busy with a client project. Can't find time for
this right now. I hope I will before end of the week. Thank your for
reporting and feel free to submit pull requests.

**Comment by djhi** [comment]
Fixed in 0.0.19

**Comment by akshaykmr** [comment]
Hey, I have the same problem.
For temp. fix I run 

``` javascript
$('select').material_select();
```

inside the template.onRendered.

**Comment by charandas** [comment]
Yes, I don't think the above fix ever worked for me.
