### ISSUE TITLE
afBooleanRadioGroup uses trueLabel for both true and false inputs

### ISSUE THREAD

**Issue by coniel** [djhi/meteor-autoform-materialize#29]
The first input in afBooleanRadioGroup should have `{{#with this.atts.falseLabel}}` instead of `{{#with this.atts.trueLabel}}`

**Comment by coniel** [comment]
Created a pull request: https://github.com/djhi/meteor-autoform-materialize/pull/30

**Comment by djhi** [comment]
Fixed in 0.0.19
