### ISSUE TITLE
missing .input-field wrapper when passing custom options

### ISSUE THREAD

**Issue by boustanihani** [djhi/meteor-autoform-materialize#34]
When passing extra options to AutoForm inside a Schema the generated quickfield won't get wrapped inside a `<div class="input-field">` as intended (check: http://materializecss.com/forms.html)

**Compare the HTML result of Size-1 & Size-2**

Reproduction deployment: http://materialize-autoform.meteor.com
Repository: https://github.com/boustanihani/materialize-autoform

``` html
<body>
    <h5 class="center">Materialize AutoForm</h5>

    <div class="row">
        <div class="col s4 offset-s4">
            {{> hello}}
        </div>
    </div>
</body>

<template name="hello">
    {{> quickForm id="tableCreate" schema="Schema.test"}}
</template>
```

``` javascript
Schema.test = new SimpleSchema({

    size1: {
        type: Number,
        label: 'Size-1',
        allowedValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    },

    size2: {
        type: Number,
        label: 'Size-2',
        allowedValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        autoform: {
            firstOption: 'Choose Size-2',
            options: 'allowed',
        }
    },

    field1: {
        type: String,
        label: 'Field-1',
    },

    field2: {
        type: String,
        label: 'Field-2',
    },
});
```

**Comment by djhi** [comment]
Can't reproduce, they are wrapped in an .input-field.

I might have fixed this with other changes, so please wait for 0.0.20

**Comment by boustanihani** [comment]
I'll check this again after updating to 0.0.20

**Comment by djhi** [comment]
0.0.20 released. Reopen this if needed

**Comment by boustanihani** [comment]
This is fixed, greeat work :+1:
