### ISSUE TITLE
TextArea should be wrapped in .input-field div

### ISSUE THREAD

**Issue by tcmal** [djhi/meteor-autoform-materialize#35]
From the materialize website:

> You must have a `.input-field` div wrapping your input and label.

**Comment by boustanihani** [comment]
Possible duplicate of https://github.com/djhi/meteor-autoform-materialize/issues/34 ??

**Comment by tcmal** [comment]
I don't think so...

**Comment by djhi** [comment]
Can't reproduce, they are wrapped in an `.input-field`.

I might have fixed this with other changes, so please wait for `0.0.20`

**Comment by byennen** [comment]
@djhi thanks for getting these PR's accepted!

**Comment by djhi** [comment]
My pleasure, keep reporting any prbs ;)
