### ISSUE TITLE
Label overlaps input with the 'disabled' attribute

### ISSUE THREAD

**Issue by kamek-pf** [djhi/meteor-autoform-materialize#40]
This is what happens when an input is created with autoform using the 'disabled' parameter :
![1](https://cloud.githubusercontent.com/assets/3883992/8389162/120cea6e-1c3a-11e5-8340-ed8c1a13dafd.png)

Here is what's expected :
![2](https://cloud.githubusercontent.com/assets/3883992/8389178/4c2db386-1c3a-11e5-9854-bc632b8a4bc1.png)

`label-class="active"` doesn't work so there is no clean workaround yet.

**Comment by byennen** [comment]
@kamek-pf having the same issue...

**Comment by djhi** [comment]
Fixed in `0.0.20` which will be released today
