### ISSUE TITLE
Support for aldeed:autoform-select2

### ISSUE THREAD

**Issue by charleshan** [djhi/meteor-autoform-materialize#41]
I'm loving the package so far. I was just wondering if it would be possible to get support for https://atmospherejs.com/aldeed/autoform-select2 or if you know any workaround, that would be great too!

**Comment by djhi** [comment]
Hi :) What is the problem exactly ? Can you create a repository reproducing what you have ?

**Comment by charleshan** [comment]
Hi @djhi, thanks for the quick response. Here's a MeteorPad reproducing the issue: http://meteorpad.com/pad/qAHKzqRD2rQcPi4yr/Materialize-autoform-select2. I also found (while I was making this for you lol) that deleting `AutoForm.setDefaultTemplate('materialize');` actually fixes this but of course, we can't do that because it' creates a lot more problems.

**Comment by charleshan** [comment]
It seems like Meteor package manager wasn't doing it's job... I found that `aldeed:autoform` was on a version that is not compatible. Problem solved.

**Comment by djhi** [comment]
Glad it worked ! I recently had many prbs too with the package manager getting old versions of some packages

**Comment by charleshan** [comment]
Actually... I thought autoform would be added as a dependency but it wasn't. I'm still get the issue. Could you take a look? http://meteorpad.com/pad/qAHKzqRD2rQcPi4yr/Materialize-autoform-select2

**Comment by djhi** [comment]
So, the select is working but you need to override select-2 css for materialize. I've never used this plugin with materialize but you can start with:

``` css
.select2-container {
  margin-top: .5em;
}
```

**Comment by charleshan** [comment]
hm... okay. I presume there isn't any plan for the package to support it then?

**Comment by djhi** [comment]
Materialize has its own dropdown mecanism for select elements. I think support for select-2 should be in a separate package.

**Comment by charleshan** [comment]
I was thinking that it could be a quick fix because the form looks good (except the right boarder) when I remove the package.

**Comment by djhi** [comment]
Sorry but I won't include compatibility fixes for other librairies in this package. Those should be provided as separate packages.
