### ISSUE TITLE
select dropdown doesnot work in firefox

### ISSUE THREAD

**Issue by piyushcoader** [djhi/meteor-autoform-materialize#42]
In firefox the the select dropdown is rendered but when i change the value the value in the dropdown is not changed. If i render the select tag without autoform i mean with only materialize package then it works fine. 
I notice when i log the console  class of dropdown list is not changed to active and disabled  whereas in the materializecss it adds the class disabled and set acitive to current selected list
Thanks,

**Comment by djhi** [comment]
The playground works fine on FF (dropdowns included):
http://autoform-materialize-playground.meteor.com/
