### ISSUE TITLE
labels are missing on select-radio

### ISSUE THREAD

**Issue by byennen** [djhi/meteor-autoform-materialize#45]
labels are missing on select-radio, and select-radio-inline

**Comment by djhi** [comment]
Yes, this is by design, take a look at the playground:

http://autoform-materialize-playground.meteor.com/
https://github.com/djhi/meteor-autoform-materialize-playground

**Comment by byennen** [comment]
@djhi I'm going to close this out. Your correct. Although, it seems a little odd at first. I've move any radio buttons that needed a label to a select dropdown, which accomplishes the same objective. Thanks again!

**Comment by alonprince** [comment]
How can I show the label? Is there have something config to figure out this problem?I don't want use dropdown instead of radio.
