### ISSUE TITLE
Question: {{atts.id}}

### ISSUE THREAD

**Issue by boustanihani** [djhi/meteor-autoform-materialize#47]
@djhi I am just curious why you defined `{{atts.id}}` as `{{atts.name}}` in:
https://github.com/djhi/meteor-autoform-materialize/blob/0.0.21/inputTypes/switch/switch.js#L35

Is it because you faced this particular issue => https://github.com/aldeed/meteor-autoform/issues/1074

I suppose this is an autoform bug right?

**Comment by djhi** [comment]
Can't remember... sorry

**Comment by boustanihani** [comment]
I mean shouldn't we make use of the autogenerated autoform-IDs when creating custom types so that there are no duplicate IDs in the DOM in case a template is rendered several times?

**Comment by Chun-Yang** [comment]
@boustanihani Can you create a pull request to demonstrate your idea? Thank you!

**Comment by boustanihani** [comment]
Usually autoform generates random IDs for all fields. But there seems to be a bug when using custom templates (https://github.com/aldeed/meteor-autoform/issues/1074) the IDs are not getting passed/generated...

I was just wondering if you faced the same issue and then decided to let `{{atts.name}}` be the field id instead of using the random id generated by autoform because it is not getting passed... I am not sure if there could be issues when we have multiple fields with the name (and the same IDs) rendered at the same time. And I assume autoform encourages us to use the autogenerated random IDs to prevent any possible issues...

When the autoform-bug is fixed I would then create a pull request for replacing the following line https://github.com/djhi/meteor-autoform-materialize/blob/0.0.21/inputTypes/switch/switch.js#L35 =>

`id: this.atts.name` would then become `id: this.atts.id`

Currently it makes no sense because `atts.id` is `undefined`.
