### ISSUE TITLE
afCheckboxGroup_materialize: Checkbox aren't checked as they should be.

### ISSUE THREAD

**Issue by kamek-pf** [djhi/meteor-autoform-materialize#49]
When using `afCheckboxGroup_materialize` to show an existing document, the checkboxes aren't checked as they are supposed to be. Looking at the template instance however, the values are correct, so it's just a matter of actually checking the checkboxes.

Here is what we did to fix it :

```
Template.afCheckboxGroup_materialize.onRendered(function () {
    var template = this;
    if (this.data.value) {
        this.data.value.forEach(function (value) {
            var selector = 'input[value="' + value + '"]';
            template.$(selector).prop('checked', true);
        });
    }
});
```

**Comment by ChJJin** [comment]
I have the same situation. 

I think this is because it miss the `checked` attribute of `itemAtts` as how the [autoform source](https://github.com/aldeed/meteor-autoform/blob/devel/inputTypes/select-checkbox/select-checkbox.js#L41-L43) do.

**Comment by serkandurusoy** [comment]
Any word on fixing this?

**Comment by kamek-pf** [comment]
For now, you can simply copy/paste the fix from the first post somewhere in your client code, but the package definitely needs a proper fix.

**Comment by serkandurusoy** [comment]
Yep, that's what I did.

**Comment by djhi** [comment]
I'll work on this issue this weekend

**Comment by djhi** [comment]
Fixed in `0.0.22` which will be published later today

**Comment by serkandurusoy** [comment]
I just upgraded to 0.0.23 and can confirm that it is _NOT_ fixed. 

I can only see my checkboxes checked if I include the following snippet:

``` javascript
Template.afCheckboxGroup_materialize.onRendered(function () {
    var template = this;
    if (this.data.value) {
        this.data.value.forEach(function (value) {
            var selector = 'input[value="' + value + '"]';
            template.$(selector).prop('checked', true);
        });
    }
});
```

**Comment by djhi** [comment]
You're right, I only applied it on the online version. Fix incoming

**Comment by serkandurusoy** [comment]
:+1:

**Comment by djhi** [comment]
I have to refactor all helpers in order for this to work. Expect a release in a few hours

**Comment by serkandurusoy** [comment]
Cool, this has now been fixed!
