### ISSUE TITLE
Select options disappear after validation error

### ISSUE THREAD

**Issue by serkandurusoy** [djhi/meteor-autoform-materialize#59]
I have a form with a select that has a long (50+) list of options (loaded dynamically).

If I submit the form when there are validation errors, then only the first ~15 options stay visible while the other options disappear.

Looking into the dom, I can see that the original select options are still there, but the generated `li` options are missing the rest.

**Comment by serkandurusoy** [comment]
Fixed by manually reinitializing material selects, but I believe this should be a part of the theme, watching for changes in reactive autoform properties and values.

**Comment by serkandurusoy** [comment]
By the way, https://github.com/djhi/meteor-autoform-materialize/pull/58 actually fixes this.

**Comment by Chun-Yang** [comment]
#58 is merged. Close this issue.
