### ISSUE TITLE
dropdowns/selects don't work

### ISSUE THREAD

**Issue by Sivli-Embir** [djhi/meteor-autoform-materialize#6]
Like the title says, selects are not working. Running `$('select').material_select();` in the console fixes it.

EDIT: also great work with this :)

**Comment by djhi** [comment]
That's strange, I use those selects in my apps and I don't have to call `material_select`

You can see the calls:
- [afSelect_materialize](https://github.com/djhi/meteor-autoform-materialize/blob/master/materialize.coffee#L125)
- [afBooleanSelect_materialize](https://github.com/djhi/meteor-autoform-materialize/blob/master/materialize.coffee#L135)
- [afSelectMultiple_materialize](https://github.com/djhi/meteor-autoform-materialize/blob/master/materialize.coffee#L145)

**Comment by Sivli-Embir** [comment]
I am calling it in a modal if that helps. But I will look into it. A quick fix works:

``` coffee
Template.Profile.rendered = -> @$('select').material_select()
```

**Comment by djhi** [comment]
Modals shouldn't be a problem

Le mer. 25 mars 2015 à 18:33, Sivli Kestanous notifications@github.com a
écrit :

**Comment by coniel** [comment]
Have a similar issue (but running `$('select').material_select();` in the console isn't fixing it). The issue only appears when the page has been refreshed by Meteor after a code change. If I do a manual refresh or navigate to another page and back it works fine.

**Comment by djhi** [comment]
@coniel, I can't reproduce this: Meteor has hot reloaded my pages multiple times and this damn select just keep working :) 
Can you tell me which version of meteor, autoform and this package you're using ?

@Kestanous: I'm going to test in modals with my materialize version of `yogiben:modals`

**Comment by coniel** [comment]
I'm on the latest version for everything.
Meteor 1.0.5
autoform 5.1.0
autoform-materialize 0.0.12

Also, it seems I was wrong about manual refreshing helping (well at least it's not helping anymore). Navigating to a different route and back makes it work though.

**Comment by djhi** [comment]
Well, just created a playground to test. Same packages configuration. Everything is working, in modals too. 

Can you guys clone and try this repo ? 

https://github.com/djhi/meteor-autoform-materialize-playground.git

PS: going to sleep now, I'll check your answers tomorrow. May the Force be with you ^^

**Comment by Sivli-Embir** [comment]
I am out for my weekend but I will check it Sunday. Don't stress it on my end, my patch works for me. I am not up to date with all the packages so that could be it. 

Cheers!

~Sivli Kestanous (cmtoups)

**Comment by coniel** [comment]
Well it works for me as well in the playground repo, so I'm not sure what's up with my own app. Anyway, my issue is not really much of a problem, they work fine in a normal user scenario. I'll let you know if I figure it out at some point. Thanks a lot for all the help and fixes today!

**Comment by Sivli-Embir** [comment]
Still not sure about this. I updated everything but the issue still there.

Not sure if it helps but, my schema is as such:

``` js
  language: {
    type: String,
    optional: true,
    label: function () { return TAPi18n.__("Language") },
    allowedValues: ['en', 'es'],
    autoform: {
      options: function () {
        return [
          { label: 'English', value: 'en' },
          { label: 'Español', value: 'es' }
        ]
      }
    }
  }
```

Again my fix works for me so don't worry about it. Very strange.

**Comment by djhi** [comment]
I added your property schema on the playground but without the label function and it worked. Can you comment it to confirm ?

This might be related to this issue in materialize [#889](https://github.com/Dogfalo/materialize/issues/889). 

The label function might run when TAPi18n switch language. Not use about this as you should have a dropdown with default language before the switch and this dropdown should simply not update labels.

**Comment by djhi** [comment]
Playground live here: http://autoform-materialize-playground.meteor.com/

**Comment by Sivli-Embir** [comment]
Thanks to #3 I found my issue. I had:

``` js
AutoForm.setDefaultTemplate('materialize');
...
AutoForm.setDefaultTemplate('bootstrap3'); //later in my code
```

Really sorry about that. Everything is working great now... I was using bootstrap & semantic ui before and apparently did not clean it up all the way.

**Comment by djhi** [comment]
No prb, glad you solved it :)

Le lun. 30 mars 2015 à 17:50, Sivli Kestanous notifications@github.com a
écrit :
