### ISSUE TITLE
Icon prefixes

### ISSUE THREAD

**Issue by donwojtallo** [djhi/meteor-autoform-materialize#60]
Is there any possibility to use a QuickField to render input with an icon prefix?
Like this:

```
{{> afQuickField name='username' icon='account_circle'}}
```

to render this:

```
<div class="input-field col s6">
      <i class="material-icons prefix">account_circle</i>
      <input id="username" type="text" class="validate">
      <label for="username">Username</label>
</div>
```

**Comment by djhi** [comment]
Not currently. I'm not sure it's possible

Le jeu. 20 août 2015 à 13:56, donwojtallo notifications@github.com a
écrit :

**Comment by donwojtallo** [comment]
It would be nice to have this feature in the future.

**Comment by Chun-Yang** [comment]
@donwojtallo can you create a new inputType and write some doc on it?
Please refer to https://github.com/djhi/meteor-autoform-materialize/tree/master/inputTypes.
We would like to merge good commits!
Thank you for your help.

**Comment by donwojtallo** [comment]
I was already thinking about this, but then I had to stop contributing for a while (not enough time). I can do this next week.

**Comment by donwojtallo** [comment]
https://github.com/djhi/meteor-autoform-materialize/pull/74
I could do this earlier, if I only knew it would be so simple. It works for me.
