### ISSUE TITLE
Autoform Materialize and Typeahead/Autocomplete

### ISSUE THREAD

**Issue by ghost** [djhi/meteor-autoform-materialize#61]
Hi there,

any suggestions on this topic?
Is there a css class for typeahead in Materialize? 
How to do this best, maybe use Meteor-Autocomplete?

Regards

**Comment by Chun-Yang** [comment]
Thank you for your help!

@der-ede This seems to be suitable for another dedicated package for that. I would like to see a package like that. I will checkout your repo if you create one. :smile: 

I have close this issue since it is not our concern.

**Comment by ghost** [comment]
Hi there,

Thank you for your response. I wish I had time for that haha.
I also have to say thank you for the package, but in my company we decided
against materialize polymers paper etc.
As I think this is a good direction for Google to put more effort into
design, it is also their first iteration and I think it is not grown up
yet. But definitely something interesting for the future.

Keep it up and
Regards

Am Montag, 14. September 2015 schrieb yang2007chun :
