### ISSUE TITLE
missing $unset for cleared pickadate fields

### ISSUE THREAD

**Issue by boustanihani** [djhi/meteor-autoform-materialize#62]
When using `pickadate` and after clearing a date field, calling `AutoForm.getFormValues('FormId').updateDoc` will not contain `$unset` for the field cleared:

``` javascript
{
    type: Date,
    autoform: {
        type: "pickadate",
        pickadateOptions: {
            //...
        }
    },
}
```

I could also do a reproduction example if needed...

**Comment by Chun-Yang** [comment]
Please reproduce the bug. Can you consider using http://meteorpad.com/?
Thank you!
