### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by serkandurusoy** [djhi/meteor-autoform-materialize#63]
Hi,

Great work!

But I do wonder if this is dead since it has been months now that there are no updates and PRs waiting.

@djhi if you don't have the time to work on this, would you consider granting write permissions to some other devs for both this repo and the atmosphere package?

**Comment by djhi** [comment]
Hi, no this project is not dead but you're right, I don't have much time. I would gladly grant permissions to other devs on the repo and atmosphere. Maybe we should create an org for it ? Are you in ?

**Comment by serkandurusoy** [comment]
This is great news.

I'm definitely in!

Although I'm not proficient enough in materializecss to oversee everything, I'd be perfectly willing to submit fixes and review PR's to help you in any way I can.

**Comment by Chun-Yang** [comment]
Hey @djhi We use materialize heavily. Do you mind grant us permissions?  https://atmospherejs.com/poetic/

**Comment by serkandurusoy** [comment]
:+1:

**Comment by djhi** [comment]
@Chun-Yang I granted poetic permissions on this package. Btw, I just saw your `react-autoform-material-ui`. I'm doing a lot of React lately so I'll definitely give it a go :+1:

**Comment by Chun-Yang** [comment]
@djhi Do you want me to commit to your github project? Or you prefer we maintain a fork? If you want me to commit to your project. Can you grant me access too?

Thanks you!

**Comment by djhi** [comment]
Ok to grant you access but can we agree to work by PRs with mutual reviews then ?

**Comment by Chun-Yang** [comment]
Awesome. I hope this works out. I will create PRs.

**Comment by serkandurusoy** [comment]
@Chun-Yang @djhi  You guys are just plain awesome! Hip hip hooray for community collaboration! :clap:
