### ISSUE TITLE
Radio select not working in meteor-autoform-materialize-playground

### ISSUE THREAD

**Issue by 0o-de-lally** [djhi/meteor-autoform-materialize#66]
Check the first radio select in the quickform example. After choosing one, you cannot de-select, or choose another.

**Comment by Chun-Yang** [comment]
@djhi Is this a meteor-autoform-materialize problem? Or the radio select is supposed to work like that?

**Comment by djhi** [comment]
This is a bug on meteor-autoform-materialize. The same happen with checkbox-select on the playground. I'll try to fix that. Thx @keyscores

**Comment by mozfet** [comment]
this is more than a year old... im closing it to make room for new issues ;)
