### ISSUE TITLE
Some interface proposals

### ISSUE THREAD

**Issue by joaobarcia** [djhi/meteor-autoform-materialize#72]
In many of the form types the visual placement of the elements does not seem the most correct:

Regarding **radio-select-inline** types, the radiobutton seems to belong to the wrong label: 
![screenshot from 2015-09-21 23 08 30](https://cloud.githubusercontent.com/assets/6717014/10006515/b5217dd6-60b5-11e5-9322-14b481a95d1c.png)

Possible fix would be changing the CSS of 

```
[type="radio"]:not(:checked) + label, [type="radio"]:checked + label {
padding-left: 35px}
```

to 

```
padding: 0px 25px 0px 30px;
```

Result:
![screenshot from 2015-09-21 23 09 21](https://cloud.githubusercontent.com/assets/6717014/10006527/db954de4-60b5-11e5-8213-9267e7596d7a.png)

Regarding **array fields** the adding/removing array options also seem too bulky and unclear. In my regard this is due to using raised buttons, as well as their placement. I would imagine flat buttons, perhaps even just with an icon would work better (as described in https://www.google.com/design/spec/components/buttons.html#). The placement of the remove button also makes it unclear about which element it refers to (the one below, or the one above)

Otherwise, thanks for the great library!

**Comment by Chun-Yang** [comment]
These are valid points. 
However, it seems these are problems of materializecss IMO. Overriding their style may lead to confusion. I would say for now we can override these styles on the project level.
