### ISSUE TITLE
Incompatible with Meteor 1.2 due less version dependency

### ISSUE THREAD

**Issue by paulgrieselhuber** [djhi/meteor-autoform-materialize#73]
While upgrading to Meteor 1.2:

```
=> Errors while initializing project:         

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_2.
Constraints on package "less":
* less@=2.5.0_2 <- top level
* less@1.0.11 <- gildaspk:autoform-modals-materialize 0.0.7
```

**Comment by Chun-Yang** [comment]
Please update to 0.0.25

**Comment by paulgrieselhuber** [comment]
At the moment it appeared that while the github repo was up to date (0.0.25), the atmosphere package was not (so updating via meteor wasn't an option). Could be mistaken, as I had to revert to 1.1 due to lots of issues with packages not supporting 1.2 yet.

**Comment by Chun-Yang** [comment]
I can confirm that the version on atmosphere is 0.0.25. You can try to manually change the version in .meteor/versions file.
