### ISSUE TITLE
Labels still visible on hidden fields using quickForm

### ISSUE THREAD

**Issue by mynameiskyleok** [djhi/meteor-autoform-materialize#77]
The field itself is hidden, however the field label itself still shows (see screenshot) using the following schema definition:

``` javascript
collectionName.attachSchema(new SimpleSchema({
    fieldName: {
        type: String,
    },
    fieldName2: {
        type: String,
        autoform: {
            type: 'hidden'
        }
    }
}));
```

![autoform-issue](https://cloud.githubusercontent.com/assets/4357572/11033667/08718b8e-86b3-11e5-8f0e-61d1fe3cc419.jpg)

**Comment by mynameiskyleok** [comment]
I'm still not sure if this is a bug or a versioning thing with meteor-autoform, but according to the meteor-autoform documentation (http://autoform.meteor.com/types --> select 'hidden' from dropdown), this is how you create a hidden field with a schema:

``` javascript
{
    typeTest: {
        type: String,
        optional: true,
        autoform: {
            afFieldInput: {
                type: "hidden"
            }
        }
    }
}
```

However, I've found that if you remove the `javascript afFieldInput` object and place the `javascript type: "hidden"` property directly in the `javascript autoform` object, the field is successfully hidden:

``` javascript
{
    typeTest: {
        type: String,
        optional: true,
        autoform: {
            type: "hidden"
        }
    }
}
```

**Comment by mozfet** [comment]
this solution also works for me.
