### ISSUE TITLE
Clicking label does not activate text input

### ISSUE THREAD

**Issue by amcneilly** [djhi/meteor-autoform-materialize#79]
I was following the tutorial http://farla.io/2015/05/18/generating-beautiful-forms-the-easy-way-with-autoform-for-meteor.html using the Meteor materialise boiler template https://materialize-boilerplate.meteor.com/.

meteor-autoform-materialize appears broken as the autoform created inputs do not activate when clicking the label. You need to click below the label to active.

Result is fustrating user experience.

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
