### ISSUE TITLE
Interface lag with arrays of objects on save

### ISSUE THREAD

**Issue by mostlyharmless2024** [djhi/meteor-autoform-materialize#80]
I'm not 100% sure but it looks like the materialize javascript initialization is re-fired each save for every form element.

While I know that probably makes sense to keep the interface up-to-date and functioning- it's causing my interface to freeze for ~1 second, like pegging the CPU to 100%.

When I remove the array field these issues go away.

Watching in dev tools I can see all of my for elements get updated 4+ times directly after a save (auto or not).

Any suggestions?

**Comment by gantrim** [comment]
I am also looking to fix this issue. I plan on submitting a pr if/when i have a fix. To save me some time, do you remember where in the code this is happening?

**Comment by mixcas** [comment]
I'm having an issue like this too. The whole interface gets frozen after i remove an element from an array.

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
