### ISSUE TITLE
Placeholders overlapping input fields

### ISSUE THREAD

**Issue by BackSpaceTech** [djhi/meteor-autoform-materialize#87]
Materialize requires labels set to "active" when using placeholders, otherwise placeholders and labels will be overlapping:
"If you are having trouble with the labels overlapping prefilled content, Try adding class="active" to the label"
Can you please consider making a change to your plugin to accommodate this?
see: http://materializecss.com/forms.html#input

**Comment by PhilippSpo** [comment]
If I remember correctly you have to call `Materialize.updateTextFields();` once the input is rendered (so in the `onRendered` callback of your template.

**Comment by 0o-de-lally** [comment]
I confirm that Materialize.updateTextFields() on rendering solves the overlapping issue.

```
Template.templateName.rendered = function(){
   Materialize.updateTextFields();
 }
```

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
