### ISSUE TITLE
input-col-class not supported

### ISSUE THREAD

**Issue by yourcontainer** [djhi/meteor-autoform-materialize#88]
`{{> afQuickField input-col-class="col s6" name='name' placeholder=''}}`

Works fine only with bootstrap,  and also if use `template="plain"`

https://github.com/djhi/meteor-autoform-materialize/blob/master/components/afFormGroup/afFormGroup.html#L3

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
