### ISSUE TITLE
Styling afQuickField Labels

### ISSUE THREAD

**Issue by boustanihani** [djhi/meteor-autoform-materialize#9]
If you look at the `Input fields` on http://materializecss.com/forms.html you will notice that the **labels get smaller on focus** but using `{{> afQuickField name='<field>'}}` combined with this package will let the labels all render small from the beginning (even without focus), is this intended? IMO, the other behaviour looks nicer :)

**Comment by djhi** [comment]
http://autoform-materialize-playground.meteor.com/

**Comment by djhi** [comment]
Make sure you have the last version of materialize

**Comment by djhi** [comment]
The repo for the playground is here: https://github.com/djhi/meteor-autoform-materialize-playground.git

I'll add it to the readme when I'll get the chance

**Comment by boustanihani** [comment]
Thanks, nice work :+1: 

I am not using `{{> quickForm}}`, I am using `{{#autoForm}}` with `{{> afQuickField}}`

Could this be the problem?

Have you tried combining `{{#autoForm}}` and `{{> afQuickField}}`?

**Comment by djhi** [comment]
I use it all the time in my apps. No prb so far

Le ven. 27 mars 2015 à 13:32, boustanihani notifications@github.com a
écrit :

**Comment by boustanihani** [comment]
Do you wrap the `{{> afQuickField}}` with something or you let it be a direct child of `{{#autoForm}}` ??

Are there any usage examples?

**Comment by djhi** [comment]
I'll add an example to the playground this afternoon. Give me a couple
hours, l need to finish my work first

**Comment by boustanihani** [comment]
Awesome :)

**Comment by djhi** [comment]
Playground repo updated

**Comment by boustanihani** [comment]
Sorry my mistake, I forgot to add `AutoForm.setDefaultTemplate('materialize')` and that was causing the issue :)

**Comment by djhi** [comment]
Glad you got it working :)

Le ven. 27 mars 2015 à 17:24, boustanihani notifications@github.com a
écrit :

**Comment by boustanihani** [comment]
Great work man :+1:
