### ISSUE TITLE
pickadate within an array type, opens a modal within the array div. See image

### ISSUE THREAD

**Issue by 0o-de-lally** [djhi/meteor-autoform-materialize#93]
When one uses a pickadate type within an array type, a UI bug appears. The modal appears within a div and the overflow cuts off the calendar box modal. See image for detail.

![screen shot 2016-03-18 at 10 00 13 am](https://cloud.githubusercontent.com/assets/1364012/13879900/421f08b8-ecf0-11e5-878b-7308b6930fc8.png)

Code example:

```
 sales: {
  type: Array,
  label: "Sales",
  optional: true
},
 'sales.$': {
   type: Object
 },
 'sales.$.value': {
    type: Number,
    label: "Sale Value",
    decimal: true
 },
 'sales.$.timeStamp': {
    label: "Sale Date",
    type: Number,
  autoform: {
      type:"pickadate"
 }
}
```

**Comment by 0o-de-lally** [comment]
This is a Materialize issue, which happens when the datepicker is attached to a parent element and not the body.

Can be fixed on line 74 with:

```
   opts = _.defaults(userOptions, {
     format: DEFAULT_PICKADATE_FORMAT_SUBMIT,
     hiddenName: true,
     closeOnSelect: true,
     container: 'body' //solves problem with being inside a a container with overflow https://github.com/Dogfalo/materialize/issues/1032
   });
```

See here: https://github.com/Dogfalo/materialize/issues/1032

**Comment by keyscores** [comment]
Actually, Adding  $('.picker').appendTo('body'); within the .render() method will cause the app to crash. Somehow it creates a memory leak. 

@djhi @Chun-Yang  Any ideas where to add the appendTo method ?

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
