### ISSUE TITLE
How to make Array type horizontal or inline?

### ISSUE THREAD

**Issue by 0o-de-lally** [djhi/meteor-autoform-materialize#94]
I've been struggling with the CSS of the Array type forms.

Has anyone here had any success making the forms within an Array type, look horizontal.

To be clear, today all input fields within an array appear line by line. I would like them on the same line.

Thanks in advance

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
