### ISSUE TITLE
layout problem when displaying group of checkboxes

### ISSUE THREAD

**Issue by adrian-gierakowski** [djhi/meteor-autoform-materialize#95]
screenshot from the playground project: 

<img width="407" alt="screen shot 2016-04-10 at 22 01 03" src="https://cloud.githubusercontent.com/assets/330177/14412687/5fb7aaf8-ff68-11e5-87aa-ab992d519977.png">

this happens both and Safari and Chrome on OSX 10.11

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
