### ISSUE TITLE
misaligned text on [ ADD + ] button for adding array elements 

### ISSUE THREAD

**Issue by adrian-gierakowski** [djhi/meteor-autoform-materialize#96]
The REMOVE button seems to have the text properly centered vertically, however on the ADD button it is a bit too low. The ADD button is a also a bit too close to the section title ( 'Emails'  ) for my taste. 

<img width="304" alt="screen shot 2016-04-10 at 22 07 51" src="https://cloud.githubusercontent.com/assets/330177/14412726/0cb24948-ff69-11e5-8b01-bf7451005dfa.png">

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
